postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=postgres
redis:
  image: redis
  ports:
    - "6379:6379"
rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
mongodb:
  image: mongo
  ports:
    - "27017:27017"
